version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    # OR use the image if already pushed: image: salahamran/kittygram_backend
    depends_on:
      - db
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    env_file:
      - .env
    restart: always
    expose:
      - "8080"  # Internal only (used by gateway)

  frontend:
    build:
      context: ./frontend
    # OR use the image if already pushed: image: salahamran/kittygram_frontend
    volumes:
      - static:/app/frontend_static/
    restart: always

  gateway:
    build: ./nginx
    # OR use the image if already pushed: image: salahamran/kittygram_gateway
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - "9001:80"   # Changed to avoid conflict with Taski (which uses 8000:80)
      - "4431:443"  # Optional, if you want SSL for Kittygram separately
    restart: always

volumes:
  static:
  media:
  pg_data:
