version: '3.8'
volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: salahamran/kittygram_final-backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/var/www/kittygram/media
    depends_on:
      - db

  frontend:
    image: salahamran/kittygram_final-frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: salahamran/kittygram_final-gateway
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles/
    depends_on:
      - backend
      - frontend

